### ISSUE TITLE
`str->base64` and `encode` do not produce the same results

### ISSUE THREAD

**Issue by JarrodCTaylor** [funcool/buddy-core#29]
Using buddy version 0.11.0 `buddy.core.codecs` the function `(str->base64 "example")` would yield the result that I expected `ZXhhbXBsZQ==`

Now using version 0.12.1 `buddy.core.codecs.base64` the function `(encode "example")` which I assume is intended to be a comparable function returns `#object[[B 0x26159658 [B@26159658]`

**Comment by niwinz** [comment]
Yes, now they return byte array instead of string, if you want the old str->base64 behavior, just declare an alias `(def str->base64 (comp codecs/bytes->str b64/encode))`.

This is done because internally (in buddy related modules) i often need a bytes output instead of the string, and doing string encoding and later back again to bytes. An other reason is because there are a lot of ways to use base64 but exposing them as `str->base64`, `str->safebase64`, `str->bbase64` becomes very unclear and inconsistent api. Now I exposes the most flexible one that just receives bytes and return bytes, and if any one want string restult, codecs/bytes->str can be used.

**Comment by JarrodCTaylor** [comment]
Makes sense, and does result in a much cleaner api design. Thanks for the response. Excellent work as always.
